# The URL the site will be built for
base_url = "https://example.com"
compile_sass = true
build_search_index = false
title = "TPW Carto"
theme = 'web'

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here

new_issue_url = "https://github.com/tpwres/teczki-polskiego-wrestlingu/issues/new"

mapobjects_path = '/objects.json'


list_pages = false
default_theme = "dark"
header_links = [
    { url = "//tpwres.pl/e/", name = "Events", icon = "calendar-1" },
    { url = "//tpwres.pl/o/", name = "Orgs", icon = "handshake" },
    { url = "//tpwres.pl/w/", name = "People", icon = "users" },
    { url = "//tpwres.pl/tt/", name = "Teams", icon = "biceps-flexed" },
    { url = "//tpwres.pl/a/", name = "Articles", icon = "book" },
    { url = "//tpwres.pl/v/", name = "Places", icon = "map-pin-house" },
    { url = "//tpwres.pl/c/", name = "Championships", icon = "trophy" },
    { url = "//mf.tpwres.pl", name = "Matchfinder", icon = "crosshair" },
    { url = "//art.tpwres.pl", name = "Artwall", icon = "image-play" },
]

footer_links = [
    { url = "//tpwres.pl/about", name = "About", icon = "info" },
    { url = "//tpwres.pl/contributing", name = "Contributing", icon = "file-pen-line" },
    { url = "//github.com/tpwres/teczki-polskiego-wrestlingu", name = "GitHub", icon = "github" },
    { url = "//tpwres.pl/atom.xml", name = "Atom Feed", icon = "rss" },
    { url = "//tpwres.pl/authors", name = "Authors", icon = "heart" },
]
mensch_theme = "theme-base-0e"
